### ISSUE TITLE
当使用tts作为网关时，记录在mysql的tick数据少了一半

### ISSUE THREAD

**Issue by 1412kid** [vnpy/vnpy_mysql#11]
![微信截图_20221225191648](https://user-images.githubusercontent.com/6511324/209465900-bd5dabda-76f9-420b-bafb-2ea8efb59e37.png)

**Comment by vnpy** [comment]
TTS免费环境提供的行情和实盘不是完全一致的，需要录制高质量的行情数据推荐用实盘账户在托管环境运行。

**Comment by vnpy** [comment]
TTS免费环境提供的行情和实盘不是完全一致的，需要录制高质量的行情数据推荐用实盘账户在托管环境运行。
