### ISSUE TITLE
[Add] 自动重连

### ISSUE THREAD

**Issue by rn7s2** [vnpy/vnpy_mysql#12]
MySQL 数据库连接在长时间不活动后会断开，在记录连续一周行情的时候很让人困扰。

通过 `ReconnectMixin` 可以让 `PeeweeMySQLDatabase` 带上自动重连的功能，如 [commit](https://github.com/rn7s2/vnpy_mysql/commit/a7b47df09e7561829e8aa34dd0d7a050b616e721)

不知道将其作为 `vnpy_mysql` 的默认行为是否合适？

**Comment by vnpy** [comment]
欢迎贡献PR！

**Comment by rn7s2** [comment]
#13

**Comment by vnpy** [comment]
感谢PR，我们测试后来合并发布（预计在3.7.0版本中）

**Comment by vnpy** [comment]
已经合并，非常感谢
