### ISSUE TITLE
mysql数据库字段类型设置错误导致数据失真

### ISSUE THREAD

**Issue by TianMingZhiZi0000** [vnpy/vnpy_mysql#14]
`vnpy_mysql.mysql_database.DbTickData`中的数据类型设置不够合理
- 在保存`m2305`合约的`2023/03/24-14:12:13`至`下午行情结束`的行情的时候,出现了成交量保存数据失真的情况,下图为对比其他数据源的截图,看起来`datetime`也是去除了一部分精度
![问题所在](https://user-images.githubusercontent.com/125286632/230765499-fb0cd166-6f3a-42ed-acf3-a31f14e2e9f2.png)
- 另外`turnover`字段也普遍存在失真的问题
![image](https://user-images.githubusercontent.com/125286632/230765561-4f856c9f-a526-4dcc-9628-c41b53f1a1ff.png)

**Comment by vnpy** [comment]
正确的数据请提供下？

**Comment by TianMingZhiZi0000** [comment]
> 正确的数据请提供下？

数据是这个
![问题所在数据](https://user-images.githubusercontent.com/125286632/230769146-89454ca9-b058-462c-aa6d-8616d2466ea4.png)
具体如下:
- 其他对比数据
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/15277/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/15277/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



TICK.m2305.ASK | TICK.m2305.ASKV | TICK.m2305.BID | TICK.m2305.BIDV | TICK.m2305.LAST | TICK.m2305.OI | DATETIME | TICK.m2305.VOLUME
-- | -- | -- | -- | -- | -- | -- | --
3518 | 478 | 3517 | 71 | 3517 | 1E+06 | 2023/03/24-14:12:13.323000 | 999971
3518 | 480 | 3517 | 75 | 3517 | 1E+06 | 2023/03/24-14:12:13.800000 | 999972
3518 | 480 | 3517 | 74 | 3517 | 1E+06 | 2023/03/24-14:12:14.307000 | 999978
3518 | 480 | 3517 | 21 | 3517 | 1E+06 | 2023/03/24-14:12:14.823000 | 1000031
3518 | 480 | 3517 | 20 | 3517 | 1E+06 | 2023/03/24-14:12:15.325000 | 1000032
3518 | 482 | 3517 | 40 | 3517 | 1E+06 | 2023/03/24-14:12:15.814000 | 1000087
3518 | 484 | 3517 | 3 | 3517 | 1E+06 | 2023/03/24-14:12:16.290000 | 1000089
3518 | 484 | 3517 | 2 | 3517 | 1E+06 | 2023/03/24-14:12:16.790000 | 1000096
3518 | 482 | 3517 | 7 | 3518 | 1E+06 | 2023/03/24-14:12:17.324000 | 1000098
3518 | 479 | 3517 | 96 | 3517 | 1E+06 | 2023/03/24-14:12:17.822000 | 1000119
3518 | 480 | 3517 | 124 | 3517 | 1E+06 | 2023/03/24-14:12:18.315000 | 1000122
3518 | 496 | 3517 | 138 | 3518 | 1E+06 | 2023/03/24-14:12:18.824000 | 1000124



</body>

</html>


- 保存的失真的数据
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/15277/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/15277/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



volume | datetime | turnover | bid_price_1 | ask_price_1 | bid_volume_1 | ask_volume_1 | last_price | open_interest
-- | -- | -- | -- | -- | -- | -- | -- | --
999971 | 2023/3/24 14:12:13.300 | 34915777670.0 | 3517 | 3518 | 71 | 478 | 3517 | 953108
999972 | 2023/3/24 14:12:13.600 | 34915812840.0 | 3517 | 3518 | 75 | 480 | 3517 | 953109
999978 | 2023/3/24 14:12:14.300 | 34916023860.0 | 3517 | 3518 | 74 | 480 | 3517 | 953113
1000030 | 2023/3/24 14:12:14.700 | 34917887870.0 | 3517 | 3518 | 21 | 480 | 3517 | 953165
1000030 | 2023/3/24 14:12:15.100 | 34917923040.0 | 3517 | 3518 | 20 | 480 | 3517 | 953165
1000090 | 2023/3/24 14:12:15.700 | 34919857390.0 | 3517 | 3518 | 40 | 482 | 3517 | 953213
1000090 | 2023/3/24 14:12:16.200 | 34919927730.0 | 3517 | 3518 | 3 | 484 | 3517 | 953213
1000100 | 2023/3/24 14:12:16.700 | 34920173920.0 | 3517 | 3518 | 2 | 484 | 3517 | 953210
1000100 | 2023/3/24 14:12:17.000 | 34920244280.0 | 3517 | 3518 | 7 | 482 | 3518 | 953208
1000120 | 2023/3/24 14:12:17.700 | 34920982850.0 | 3517 | 3518 | 96 | 479 | 3517 | 953214
1000120 | 2023/3/24 14:12:18.100 | 34921088360.0 | 3517 | 3518 | 124 | 480 | 3517 | 953215
1000120 | 2023/3/24 14:12:18.800 | 34921158710.0 | 3517 | 3518 | 138 | 496 | 3518 | 953216



</body>

</html>

成交量大于1000000后就出现了这个问题

**Comment by vnpy** [comment]
收到，我们来处理下

**Comment by vnpy** [comment]
turnover精度不足的问题已经修复，由于数据列的类型由FloatField改为DoubleField，需要做一次数据迁移：

1. 导出数据保存到文件
2. 删除原有数据库（或者重命名作为备份）
3. 更新vnpy_mysql模块后，重启Trader创建新数据库
4. 重新导入1中导出的数据

另外CTP的时间戳只精确到百位毫秒，因此图中那个精确到个位毫秒的时间戳可能是本地时间，这块不是数据库的问题了。

**Comment by TianMingZhiZi0000** [comment]
> turnover精度不足的问题已经修复，由于数据列的类型由FloatField改为DoubleField，需要做一次数据迁移：
> 
> 1. 导出数据保存到文件
> 2. 删除原有数据库（或者重命名作为备份）
> 3. 更新vnpy_mysql模块后，重启Trader创建新数据库
> 4. 重新导入1中导出的数据
> 
> 另外CTP的时间戳只精确到百位毫秒，因此图中那个精确到个位毫秒的时间戳可能是本地时间，这块不是数据库的问题了。

感谢修复~
图中的毫秒时间戳是不是本地时间没有验证,`vnpy_ctp.ctp_gateway.onRtnDepthMarketData`中的`data['UpdateMillisec']`是三位有效数字,在后续的处理中,只保留了一位有效数字,可能是当作传入的是6位有效数字处理了.这个已经在vnpy_ctp下提交issue.
